### ISSUE TITLE
Jool Installation fails via vagrant-start script

### ISSUE THREAD

**Issue by mmueen** [leblancd/kube-v6#12]
Background:
Installation on Windows 10, laptop, HP, core i7, 16 GB memory
Virtual box version 6.0.6
Vagrant version 2.2.4
Date: 05/13/2019

Problem:
The automated installation via vagrant-start script fails when its installing jool. It fails to find the directory and exits. The complete logs are attached in the zip file.

`    k86-nat64: DKMS: install completed.

    k86-nat64: + echo 'Compiling and installing Jool'\''s user binaries'

    k86-nat64: Compiling and installing Jool's user binaries

    k86-nat64: + sudo chown -R vagrant:vagrant /home/vagrant/Jool

    k86-nat64: + cd /home/vagrant/Jool/usr

    k86-nat64: /tmp/vagrant-shell: line 31: cd: /home/vagrant/Jool/usr: No such file or directory

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

[jool_failure_logs.zip](https://github.com/leblancd/kube-v6/files/3175168/jool_failure_logs.zip)

**Comment by etobgra** [comment]
any update? I have the same issue

**Comment by mmueen** [comment]
You can fix this by changing the file in provision/provision_nat64.sh..
Jool is downloaded in /home/vagrant/Jool .. not Jool/usr. 
Update all references in this file to /home/vagrant/Jool and it should proceed.

**Comment by mmueen** [comment]
Furthermore, the current version of Jool is 4.0.1, which requires a different setup . The vagrant files here were designed with v3.x .. if you go with current version of Jool .. you'd needto setup jool yourself as it will not work .. what I did was that I downloaded the older version of jool (3.5.7) in the provision_nat64.sh .. 

This is original

```
if [ ! -d "/home/vagrant/Jool" ]; then
	echo "Downloading Jool"
	git clone https://github.com/NICMx/Jool.git /home/vagrant/Jool.tmp
	mv /home/vagrant/Jool.tmp /home/vagrant/Jool
fi
```

I changed it to

```
if [ ! -d "/home/vagrant/Jool" ]; then
	echo "Downloading Jool"
	echo "git clone https://github.com/NICMx/Jool.git /home/vagrant/Jool.tmp"
	echo "mv /home/vagrant/Jool.tmp /home/vagrant/Jool"
	wget -O /tmp/jool.zip https://github.com/NICMx/Jool/archive/v3.5.7.zip
	unzip /tmp/jool.zip -d /tmp/
	mv /tmp/Jool-3.5.7/ /home/vagrant/Jool
	
fi
```

it worked after that.

PS. If you do this then you dont need to remove the usr as mentioned in my last comment.
