### ISSUE TITLE
Create Vagrantfile to setup the environment

### ISSUE THREAD

**Issue by aojea** [leblancd/kube-v6#8]
It will be nice to have a Vagrantfile that allows spawning the environment automatically

**Comment by leblancd** [comment]
@aojea - Yes, absolutely. Someone had merged in a Vagrantfile setup in this github repo, and I inadvertently deleted it. We're working on restoring this.

**Comment by leblancd** [comment]
@aojea - In the meantime, perhaps you can use the diffs for the merge that I inadvertently deleted, which are here?:
    https://github.com/leblancd/kube-v6/pull/6/files

**Comment by aojea** [comment]
@leblancd I submitted a new PR to recover all files from #6

**Comment by aojea** [comment]
Vagrant work done by @Oryon recover
